# Generated by Django 4.2.7 on 2025-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('in3', models.TimeField(blank=True, null=True)),
                ('out3', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('-0.5', 'Half Day'), ('-1', 'Full Day Deduction')], default='P', max_length=5)),
                ('supervisor_remarks', models.TextField(blank=True, null=True)),
                ('employee_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField()),
                ('accepted_rows', models.IntegerField()),
                ('rejected_rows', models.IntegerField()),
                ('error_file', models.FileField(blank=True, null=True, upload_to='upload_errors/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
