# Generated by Django 4.2.7 on 2025-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
